#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""v1.2 压缩收尾：把正文从 ~6,294 词（Word 口径）压到 <6,000。
每条替换逐一断言命中，任何一条未命中即报错退出（避免静默漏改）。"""
import re, sys, io

P = "学生3_LIHC_MRG预后_SCI稿件_v1.2.md"
t = open(P, encoding="utf-8").read()

PAIRS = [
# ---- 结果小节标题精简 ----
("### 3.1 Univariate screening identifies 23 survival-associated MRGs, of which five survive correction",
 "### 3.1 Univariate screening"),
("### 3.2 Model A: the full-panel index separates survival but is over-parameterised",
 "### 3.2 Model A: the full-panel index"),
("### 3.3 Model B: stability selection compresses the index to two genes, KIF15 and MAFG",
 "### 3.3 Model B: stability selection compresses the index to two genes"),
("### 3.4 MRG-2 is independent of AJCC stage and histological grade in the discovery cohort",
 "### 3.4 Independence from stage and grade"),
("### 3.5 MRG-2 is proliferation-adjacent, and its discrimination is not distinguishable from a proliferation score",
 "### 3.5 Proliferation overlap"),
("### 3.6 External validation: MRG-2 does not transport",
 "### 3.6 External validation"),
("### 3.8 Mutation profiling places the high-risk group in the TP53-mutated compartment, with one discordant observation",
 "### 3.8 Mutation profiling"),
("### 3.9 Tumour-versus-normal expression of the panel",
 "### 3.9 Tumour-versus-normal expression"),
# ---- 方法小节标题 ----
("### 2.7 Adjustment for stage and grade (both models)", "### 2.7 Adjustment for stage and grade"),
("### 2.8 Comparison against a proliferation score (both models)", "### 2.8 Proliferation score"),
("### 2.10 Somatic mutation analysis, tumour-versus-normal expression, and software",
 "### 2.10 Mutation, tumour-versus-normal expression, and software"),

# ---- 引言 ----
("""Mitoxyperilysis is a cell-death modality described in 2025 that is executed precisely through that axis. Wang and colleagues showed that innate immune stimulation combined with metabolic disruption — lipopolysaccharide together with carbon starvation — kills macrophages by a route independent of caspases, pyroptosis, PANoptosis, necroptosis, ferroptosis and oxeiptosis [11]. The execution sequence runs from BAX/BAK1/BID-dependent mitochondrial oxidative stress [12,13] to prolonged mitochondria–plasma-membrane contact, which the authors named mitoxyperiosis; sustained apposition causes local oxidative membrane damage and, ultimately, lysis [11]. Plasma-membrane rupture in programmed cell death is an actively regulated step, the NINJ1 pore being its best-characterised executor [14]. mTORC2 acts as a permissive switch: mTOR inhibition lets lamellipodia retract and pulls mitochondria away from the membrane, preserving integrity [11,15,16], and mTORC2 has independently been linked to mitochondrial fission and to ferroptosis suppression [17,18]. A mitoxyperilysis-related signature has already been reported in colorectal cancer, where it stratifies prognosis and identifies an immune-remodelled aggressive ecosystem [19,20,21]. That study establishes that the concept transfers from macrophages to bulk tumour transcriptomes, and it means that the present work cannot claim priority for a mitoxyperilysis-related prognostic model as such.""",
 """Mitoxyperilysis is a cell-death modality described in 2025 that is executed through that axis. Wang and colleagues showed that innate immune stimulation combined with metabolic disruption — lipopolysaccharide with carbon starvation — kills macrophages by a route independent of caspases, pyroptosis, PANoptosis, necroptosis, ferroptosis and oxeiptosis [11]. The execution sequence runs from BAX/BAK1/BID-dependent mitochondrial oxidative stress [12,13] to prolonged mitochondria–plasma-membrane contact, which the authors named mitoxyperiosis; sustained apposition causes local oxidative membrane damage and lysis [11]. Plasma-membrane rupture in programmed cell death is an actively regulated step, the NINJ1 pore being its best-characterised executor [14]. mTORC2 acts as a permissive switch: mTOR inhibition lets lamellipodia retract and pulls mitochondria away from the membrane, preserving integrity [11,15,16], and mTORC2 has independently been linked to mitochondrial fission and to ferroptosis suppression [17,18]. A mitoxyperilysis-related signature has already been reported in colorectal cancer, where it stratifies prognosis and identifies an immune-remodelled aggressive ecosystem [19,20,21]; the concept therefore transfers from macrophages to bulk tumour transcriptomes, but the present work cannot claim priority for such a model."""),

("""HCC is also, unusually among solid tumours, defined by its metabolic context. The liver is the principal site of gluconeogenesis, amino-acid catabolism and lipid handling; HCC redirects these pathways towards biosynthesis and towards a redox state in which glutathione and thioredoxin buffering are chronically engaged [7,8]. The therapeutic backbone is itself redox-active: sorafenib kills HCC cells in part by generating mitochondrial reactive oxygen species and by interfering with the unfolded-protein response, and resistance to it is accompanied by a measurable shift in redox metabolism [9,10]. A gene programme that reports on mitochondrial oxidative stress should therefore be informative in this tumour type.""",
 """HCC is also, unusually among solid tumours, defined by its metabolic context. The liver is the principal site of gluconeogenesis, amino-acid catabolism and lipid handling; HCC redirects these pathways towards biosynthesis and towards a redox state in which glutathione and thioredoxin buffering are chronically engaged [7,8]. The therapeutic backbone is itself redox-active: sorafenib kills HCC cells in part by generating mitochondrial reactive oxygen species and by interfering with the unfolded-protein response, and resistance to it is accompanied by a shift in redox metabolism [9,10]. A gene programme reporting on mitochondrial oxidative stress should therefore be informative in this tumour type."""),

("""Most transcriptomic prognostic signatures published in this space never report an external test, and those that do rarely report it when it fails. We designed this study around replication rather than discovery, deriving a prognostic index from the full MRG panel in TCGA-LIHC and re-deriving it with LASSO-Cox and bootstrap stability selection, and then subjecting the compressed score to four questions in sequence: does it survive a *nested* estimate of optimism, in which the whole selection procedure is repeated inside every cross-validation fold; is the stability threshold itself reproducible under an independent bootstrap seed; does it beat random panels of the same size; and does it transport to an independent cohort with the coefficients frozen. Two of the four answers are uncomfortable, and we report them as they stand.""",
 """Most transcriptomic prognostic signatures published in this space never report an external test, and those that do rarely report it when it fails. We therefore designed this study around replication rather than discovery. We derive a prognostic index from the full MRG panel in TCGA-LIHC, re-derive it with LASSO-Cox and bootstrap stability selection, and subject the compressed score to four questions in sequence: does it survive a *nested* estimate of optimism, in which the whole selection procedure is repeated inside every cross-validation fold; is the stability threshold reproducible under an independent bootstrap seed; does it beat random panels of the same size; and does it transport to an independent cohort with the coefficients frozen. Two of the four answers are uncomfortable."""),

# ---- 方法 ----
("""The apparent C-index of a model whose genes were selected on the full dataset is optimistic. We therefore repeated the *entire* Model B procedure — LASSO path, 1-SE rule, 200-bootstrap stability selection at π ≥ 0.75 and the multivariable fit — inside each training fold of a 10-fold split and applied the resulting coefficients to the held-out fold. The same machinery was applied to the Model A pipeline so that the two are compared on equal terms, and the split was fixed by a single seed so that both see the same partition.""",
 """The apparent C-index of a model whose genes were selected on the full dataset is optimistic. We therefore repeated the *entire* Model B procedure — LASSO path, 1-SE rule, 200-bootstrap stability selection at π ≥ 0.75 and the multivariable fit — inside each training fold of a 10-fold split, applied the resulting coefficients to the held-out fold, and did the same for the Model A pipeline so that the two are compared on equal terms. A single seed fixed the split, so both models see the same partition."""),

("""To ask whether a two-gene score does anything an arbitrary pair of panel genes would not, 3,000 random pairs were drawn from the evaluable panel without replacement, a two-gene multivariable Cox model was fitted in each cohort, and the apparent C-index of each pair was recorded; the observed MRG-2 value is reported as a percentile and as the proportion of panels matching or beating it. Because the benchmark uses the frozen score it does not price the gene-selection step — that is the role of the nested cross-validation (Section 2.5).""",
 """To ask whether a two-gene score does anything an arbitrary pair of panel genes would not, 3,000 random pairs were drawn from the evaluable panel without replacement, a two-gene Cox model was fitted in each cohort, and the apparent C-index of each pair was recorded; the observed MRG-2 value is reported as a percentile. Because the benchmark uses the frozen score it does not price the gene-selection step — that is the role of the nested cross-validation (Section 2.5)."""),

("""Multivariable Cox models of the form score + age + sex were extended by adding AJCC stage III–IV and histological grade G3–G4, and both the continuous score (per 1 SD) and the binary risk group were tested. The available covariates differed between cohorts — AJCC stage and grade in TCGA-LIHC; age, sex, TNM stage III–IV and array platform in GSE14520 — so the adjusted external model is necessarily the simpler of the two.""",
 """Multivariable Cox models of the form score + age + sex were extended by adding AJCC stage III–IV and grade G3–G4, and both the continuous score (per 1 SD) and the binary risk group were tested. The available covariates differed between cohorts — stage and grade in TCGA-LIHC; age, sex, TNM stage III–IV and platform in GSE14520 — so the adjusted external model is necessarily the simpler of the two."""),

("""k-means clustering (k = 2, 3, 4) was run on panel-gene expression with multiple random initialisations and the solution chosen by silhouette width. Eleven immune features (Table 6) were scored as the mean Z-score of 4–6 marker genes each (ssGSEA-lite) [32] and compared between risk groups by the Mann–Whitney U test. This is a marker-mean proxy, not a deconvolution, and it is confounded by global expression shifts; because eleven comparisons are made, Benjamini–Hochberg adjustment is reported alongside the raw values and interpretation is restricted to features that survive it.""",
 """k-means clustering (k = 2, 3, 4) was run on panel-gene expression and the solution chosen by silhouette width. Eleven immune features (Table 6) were scored as the mean Z-score of 4–6 marker genes each (ssGSEA-lite) [32] and compared between risk groups by the Mann–Whitney U test. This is a marker-mean proxy, not a deconvolution; because eleven comparisons are made, Benjamini–Hochberg adjustment is reported alongside the raw values and interpretation is restricted to features that survive it."""),

# ---- 结果 ----
("""L2-penalised multivariable Cox regression on the 23 univariate hits retained all 23 genes (Table 2). Median dichotomisation produced 180 high-risk and 180 low-risk patients. High-risk patients had substantially worse OS (median 35.8 vs 80.7 months; HR 1.87 per SD, 95% CI 1.56–2.24; log-rank *P* = 1.9×10⁻⁶; Figure 1B–D), with an apparent C-index of 0.684 (95% CI 0.625–0.733) and a mean time-dependent AUC of 0.733 (1/3/5-year AUC 0.772 / 0.718 / 0.720; Figure 2A).""",
 """L2-penalised multivariable Cox regression on the 23 univariate hits retained all 23 genes (Table 2). Median dichotomisation produced 180 high-risk and 180 low-risk patients. High-risk patients had substantially worse OS (median 35.8 vs 80.7 months; HR 1.87 per SD, 95% CI 1.56–2.24; log-rank *P* = 1.9×10⁻⁶; Figure 1B–D), an apparent C-index of 0.684 (95% CI 0.625–0.733) and a mean time-dependent AUC of 0.733 (1/3/5-year 0.772 / 0.718 / 0.720; Figure 2A)."""),

("""Three properties distinguish MRG-2 from Model A. Both coefficients are significant and agree in direction with their univariate estimates; the two genes are only weakly correlated with one another, so the coefficients can be interpreted individually; and the **EPV ratio is 64.5** (129 deaths, 2 terms) against 5.6 for Model A — an elevenfold increase in evidence per parameter.""",
 """Three properties distinguish MRG-2 from Model A. Both coefficients are significant and agree in direction with their univariate estimates; the two genes are only weakly correlated, so the coefficients can be interpreted individually; and the **EPV ratio is 64.5** (129 deaths, 2 terms) against 5.6 for Model A."""),

("""**Benchmark against random panels.** In the discovery cohort MRG-2 is nonetheless exceptional among two-gene panels: against 3,000 random pairs drawn from the same 91 genes (mean C-index 0.5608, SD 0.0333, 95th percentile 0.6172), the observed 0.6767 exceeded **every one** of them (Figure 5C, blue). That is a strong in-sample result, and it does not price the selection step — a distinction that becomes decisive in Section 3.6.""",
 """**Benchmark against random panels.** In the discovery cohort MRG-2 is nonetheless exceptional among two-gene panels: against 3,000 random pairs from the same 91 genes (mean C-index 0.5608, SD 0.0333, 95th percentile 0.6172) the observed 0.6767 exceeded **every one** of them (Figure 5C). That is a strong in-sample result that does not price the selection step — a distinction decisive in Section 3.6."""),

("""**GSE14520 (n = 242 tumours, 96 deaths, median follow-up 57.0 months).** Sixty-five of the 92 panel genes were represented on the Affymetrix platform, including both MRG-2 genes (KIF15, probe 219306_at; MAFG, probe 204970_s_at), and 19 of the 23 Model A genes. With coefficients frozen from the discovery cohort and expression standardised within the validation cohort:""",
 """**GSE14520 (n = 242 tumours, 96 deaths, median follow-up 57.0 months).** Sixty-five of the 92 panel genes were represented on the Affymetrix platform, including both MRG-2 genes (KIF15, probe 219306_at; MAFG, probe 204970_s_at), and 19 of the 23 Model A genes:"""),

("""MRG-2 **failed to replicate**. Its C-index confidence interval includes 0.5, its hazard ratio is not significant, and after adjustment for age, sex, TNM stage III–IV and array platform the score is clearly null (HR 1.05, *P* = 0.63) while stage remains strongly prognostic (HR 3.04, *P* < 0.001). Restricting to the larger platform alone (GPL3921, n = 221 tumours, 85 deaths) gives C-index 0.548, unchanged. The 23-gene Model A did replicate, weakly but significantly, at C-index 0.577 — the paradoxical outcome that the *over-parameterised* model transported and the *parsimonious* one did not.""",
 """MRG-2 **failed to replicate**. Its C-index confidence interval includes 0.5, its hazard ratio is not significant, and after adjustment for age, sex, TNM stage III–IV and platform the score is clearly null (HR 1.05, *P* = 0.63) while stage remains strongly prognostic (HR 3.04, *P* < 0.001). Restricting to the larger platform alone (GPL3921, n = 221 tumours, 85 deaths) gives C-index 0.548. The 23-gene Model A did replicate, weakly but significantly, at 0.577 — the paradoxical outcome that the *over-parameterised* model transported and the *parsimonious* one did not."""),

("""The CTNNB1 observation runs the other way, and it is not an unresolved curiosity. CTNNB1-mutant HCC is conventionally the *better*-prognosis, well-differentiated subclass, and β-catenin activation drives immune escape [8,36], yet CTNNB1 mutation is enriched — modestly — in the *high*-risk group. **It is evidence that the score is not tracking a single coherent biological axis.** A score that is high both in TP53-mutant tumours and in CTNNB1-mutant tumours is not measuring TP53-driven proliferation specifically. This is consistent with the external failure in Section 3.6 and should be read together with it.""",
 """The CTNNB1 observation runs the other way, and it is not an unresolved curiosity. CTNNB1-mutant HCC is conventionally the *better*-prognosis, well-differentiated subclass, and β-catenin activation drives immune escape [8,36], yet CTNNB1 mutation is modestly enriched in the *high*-risk group. **That is evidence the score is not tracking a single coherent biological axis:** a score high in both TP53-mutant and CTNNB1-mutant tumours is not measuring TP53-driven proliferation specifically. It is consistent with the external failure in Section 3.6."""),

("""Using the cBioPortal reference-normal Z-score profile, 22 of the 91 panel genes were over-expressed in tumour relative to reference normal liver (mean Z > 1) and 11 were under-expressed (mean Z < −1), with a median Z across the panel of 0.219 (Figure 6). Because the PanCancer Atlas LIHC cohort contains only primary solid tumours, this is a cross-database contrast against an external normal reference rather than a within-cohort comparison, and it is descriptive only.""",
 """Using the cBioPortal reference-normal Z-score profile, 22 of the 91 panel genes were over-expressed in tumour relative to reference normal liver (mean Z > 1) and 11 under-expressed (mean Z < −1), with a median Z of 0.219 (Figure 6). Because the PanCancer Atlas LIHC cohort contains only primary solid tumours, this is an external-reference comparison and is descriptive only."""),

# ---- 讨论 ----
("""We begin with the part that worked. The full-panel index was the natural first attempt: 23 univariate hits, a ridge penalty to handle collinearity, and an apparent C-index of 0.684. Two things about it were wrong. With 23 coefficients fitted on 129 deaths the EPV ratio was 5.6, half the conventional threshold [29,30]; and under the penalty no coefficient was individually significant, so the fitted weights carry no interpretable biology. It ranked patients acceptably — median survival 80.7 versus 35.8 months — but it did so by distributing a shared signal across collinear terms. Compression was therefore not an aesthetic preference. A pure LASSO-plus-1-SE rule did not deliver it: the cross-validation curve peaks at 11 genes and declines monotonically as the penalty is relaxed, and the 1-SE rule selected nine genes only 0.49 SE below that maximum. Sparsity came instead from asking which genes were selected *repeatedly*. Across 200 bootstraps, KIF15 was chosen in 91% of resamples and MAFG in 78%, while the median model contained 11 genes. Stability, not penalty strength, identified the core.""",
 """We begin with the part that worked. The full-panel index was the natural first attempt: 23 univariate hits, a ridge penalty for collinearity, and an apparent C-index of 0.684. Two things about it were wrong. With 23 coefficients fitted on 129 deaths the EPV ratio was 5.6, half the conventional threshold [29,30]; and under the penalty no coefficient was individually significant, so the fitted weights carry no interpretable biology. It ranked patients acceptably — median survival 80.7 versus 35.8 months — by distributing a shared signal across collinear terms, so compression was not an aesthetic preference. A pure LASSO-plus-1-SE rule did not deliver it: the cross-validation curve peaks at 11 genes and declines monotonically as the penalty is relaxed, and the 1-SE rule selected nine genes only 0.49 SE below that maximum. Sparsity came from asking which genes were selected *repeatedly*: across 200 bootstraps KIF15 was chosen in 91% of resamples and MAFG in 78%, while the median model contained 11 genes. Stability, not penalty strength, identified the core."""),

("""The two-gene score was better in every respect that matters for a prognostic index in the discovery data. Its coefficients are both significant and directionally consistent with their univariate estimates, so they can be read; the EPV ratio rises from 5.6 to 64.5; it matches the full-panel model's discrimination with two parameters instead of 23; it does not absorb AJCC stage; and it beat all 3,000 random two-gene panels we drew. Every one of those statements is true, and none of them predicted what happened next.""",
 """The two-gene score was better in every respect that matters for a prognostic index in the discovery data: its coefficients are significant and directionally consistent with their univariate estimates, so they can be read; the EPV ratio rises from 5.6 to 64.5; it matches the full-panel model's discrimination with two parameters instead of 23; it does not absorb AJCC stage; and it beat all 3,000 random two-gene panels we drew. Every one of those statements is true, and none of them predicted what happened next."""),

("""What happened next is the substance of this paper. Fully nested cross-validation — repeating the whole procedure inside every fold — cut both models to about 0.58 and made them indistinguishable from each other. That is not a failure of the compression argument; it is a demonstration that the *apparent* superiority of both models over chance was largely selection optimism, and that a study reporting only apparent C-indices in this design is reporting an artefact. Repetition of the bootstrap under ten independent seeds then showed that MAFG's stability is a threshold artefact: its π ranges from 0.690 to 0.805 across seeds and falls below the prespecified 0.75 in two of them, at which point the "two-gene signature" is a one-gene signature. KIF15, by contrast, never fell below 0.875. We had reported a two-gene score; the data support one robustly stable gene and one threshold-marginal gene.""",
 """What happened next is the substance of this paper. Fully nested cross-validation cut both models to about 0.58 and made them indistinguishable — not a failure of the compression argument, but a demonstration that the *apparent* superiority of both models over chance was largely selection optimism, and that a study reporting only apparent C-indices in this design is reporting an artefact. Repetition of the bootstrap under ten seeds then showed MAFG's stability to be a threshold artefact: its π ranges from 0.690 to 0.805 and falls below the prespecified 0.75 in two seeds, at which point the "two-gene signature" is a one-gene signature, whereas KIF15 never fell below 0.875. We had reported a two-gene score; the data support one robustly stable gene and one threshold-marginal gene."""),

("""The external test settled it. In GSE14520 — 242 tumours, 96 deaths, median follow-up 57 months, the standard resource for this purpose — the frozen MRG-2 score gave a C-index of 0.551, a hazard ratio of 1.14 that was not significant, an adjusted hazard ratio of 1.05, and a position at the 47th percentile of 3,000 random two-gene panels. In the same cohort a generic 20-gene proliferation score reached 0.596 and a log-rank *P* of 7.2×10⁻⁴. The ordering that held in TCGA — MRG-2 above proliferation — inverted in validation. That inversion, together with the monotone decline from 0.677 to 0.576 to 0.551, is what selection optimism looks like when it is measured instead of assumed.""",
 """The external test settled it. In GSE14520 — 242 tumours, 96 deaths, the standard resource for this purpose — the frozen MRG-2 score gave a C-index of 0.551, a non-significant hazard ratio of 1.14, an adjusted hazard ratio of 1.05, and a position at the 47th percentile of 3,000 random two-gene panels, while a generic 20-gene proliferation score in the same cohort reached 0.596 and a log-rank *P* of 7.2×10⁻⁴. The ordering that held in TCGA — MRG-2 above proliferation — inverted in validation. That inversion, with the monotone decline from 0.677 to 0.576 to 0.551, is what selection optimism looks like when it is measured instead of assumed."""),

("""What is specific to HCC, and what was not expected from the glioma analysis of the same panel, remains worth recording even though it did not translate externally. Three of the five genes that survive multiple-testing correction are redox genes — MAFG, TXNRD1 and OSGIN2 — and MAFG, the marginal member of the score, is a small-Maf protein that heterodimerises with NRF2 and drives antioxidant-response-element transcription [33,34]. In a tumour whose therapeutic backbone kills through mitochondrial reactive oxygen species and whose resistance is redox-mediated [9,10], a prognostic signal led by the redox arm is biologically coherent. But coherence is not transport, and the redox reading rests on a gene whose own selection stability is threshold-dependent. The panel supplied the selection signal; the pathway's machinery partially survived into the score; that is as far as the data take us, and it is not far enough to call the score a readout of mitoxyperilysis.""",
 """What is specific to HCC, and was not expected from the glioma analysis of the same panel, remains worth recording even though it did not translate externally. Three of the five genes surviving multiple-testing correction are redox genes — MAFG, TXNRD1 and OSGIN2 — and MAFG, the marginal member of the score, is a small-Maf protein that heterodimerises with NRF2 to drive antioxidant-response-element transcription [33,34]. In a tumour whose therapeutic backbone kills through mitochondrial reactive oxygen species and whose resistance is redox-mediated [9,10], a prognostic signal led by the redox arm is biologically coherent. But coherence is not transport, and the redox reading rests on a gene whose own selection stability is threshold-dependent. The panel supplied the selection signal and the pathway's machinery partially survived into the score; that is as far as the data take us."""),

("""Seven limitations bound the interpretation. First, and most importantly, the compressed score failed external validation; every statement in Sections 3.3–3.5 is a statement about the discovery cohort and none of them should be generalised. Second, the discovery cohort is modest (129 deaths), so the apparent C-index of 0.677 retained about 0.10 units of optimism, as the nested analysis quantifies; the external value is the one to carry forward. Third, the two genes are not equally supported by the data: KIF15 is stable under every seed, MAFG is not. Fourth, the discovery and validation systems are mismatched — the panel came from mouse macrophages under acute starvation, the target tissue is human bulk tumour, and neither retained gene is a pathway executioner — and the external platform (Affymetrix HG-U133A) is older and less sensitive than RNA sequencing, which may depress measured discrimination for reasons unrelated to biology; we cannot separate those two explanations. Fifth, no within-cohort tumour-versus-normal comparison is possible in the PanCancer Atlas LIHC cohort, and the reference-normal profile used in its place draws on a different normal-tissue resource, so Section 3.9 is descriptive only. Sixth, the immune analysis is a marker-mean proxy, not corrected for tumour purity and not a deconvolution. Seventh, no prospective or decision-impact analysis was performed and no clinical utility is claimed for any score in this paper — including for a drug-sensitivity analysis (GDSC/CTRP), which we omit because cell-line pharmacogenomic resources are not patient-matched to these cohorts and predicted IC₅₀ values from a fitted model are extrapolation rather than observation.""",
 """Seven limitations bound the interpretation. First, and most importantly, the compressed score failed external validation; every statement in Sections 3.3–3.5 concerns the discovery cohort and none should be generalised. Second, the discovery cohort is modest (129 deaths), so the apparent C-index of 0.677 retained about 0.10 units of optimism; the external value is the one to carry forward. Third, the two genes are not equally supported: KIF15 is stable under every seed, MAFG is not. Fourth, the discovery and validation systems are mismatched — the panel came from mouse macrophages under acute starvation, the target tissue is human bulk tumour, neither retained gene is a pathway executioner, and the external platform (Affymetrix HG-U133A) is older and less sensitive than RNA sequencing; we cannot separate those explanations. Fifth, no within-cohort tumour-versus-normal comparison is possible, so Section 3.9 is descriptive only. Sixth, the immune analysis is a marker-mean proxy, not corrected for tumour purity and not a deconvolution. Seventh, no prospective or decision-impact analysis was performed and no clinical utility is claimed for any score in this paper — including for a drug-sensitivity analysis (GDSC/CTRP), which we omit because cell-line pharmacogenomic resources are not patient-matched to these cohorts and predicted IC₅₀ values from a fitted model are extrapolation rather than observation."""),
]

fail = []
for old, new in PAIRS:
    if old not in t:
        fail.append(old[:70])
    else:
        t = t.replace(old, new, 1)

if fail:
    print("❌ 未命中：")
    for f in fail:
        print("   ", f)
    sys.exit(1)

open(P, "w", encoding="utf-8").write(t)
print(f"✅ 全部 {len(PAIRS)} 处替换成功")
